name: Tests

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: [8.2, 8.3, 8.4]
        stability: [lowest, stable]

    name: ${{ matrix.stability }} (${{ matrix.php }})

    steps:
      - name: ğŸ“‚ Checkout code
        uses: actions/checkout@v4

      - name: ğŸ˜ Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcov
          coverage: pcov
          ini-values: pcov.enabled=1, pcov.directory=src

      - name: âš¡ Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache/files
          key: php-${{ matrix.php }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: php-${{ matrix.php }}-composer-

      - name: ğŸ“¦ Install dependencies
        run: composer update --prefer-${{ matrix.stability }} --prefer-dist --no-interaction --no-progress

      - name: ğŸ¨ Check Linting
        if: matrix.php == '8.4' && matrix.stability == 'stable'
        run: vendor/bin/pint --test

      - name: ğŸ” Static Analysis
        run: vendor/bin/phpstan analyse --no-progress

      - name: ğŸ§ª Run Tests
        run: vendor/bin/phpunit --coverage-text

